# Generated by Django 2.2.2 on 2019-06-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='world',
            new_name='word',
        ),
    ]
